### PR TITLE
Add Rspec and Factroy Girl gems

### PR DESCRIPTION
**Pull request by mwoerner1990**
https://trello.com/c/wF605bdV/5-setup-install-rspec

Added Rspec and Factory Girl gems

### CODE REVIEW

**Comment by terrams** [comment]
Nice Job Miles!

**Comment by AaronOoooo** [comment]
Wow! That is cool!

**Comment by ejb332** [comment]
Way too sexy for this repo

**Comment by SplashGordonMD** [comment]
;-) Well done

**Comment by thaker-nish** [comment]
So many gems! :)

**Comment by terrams** [comment]
👍

**Comment by AaronOoooo** [comment]
🥇 Woo hoo!

**Comment by ceedubs84** [comment]
👍

**Comment by SplashGordonMD** [comment]
Nice
 😁

*S. Casey Platt*
*612 S. Laflin #E*
*Chicago IL 60607*

*312-320-4016*

**Pull request merged**
